In [1]:
import torch
from torch.autograd import Variable

$z = (x+2)^2+3$\
$z'=2(x+2)$\
If x = 2, $z'=8$

In [11]:
x = Variable(torch.Tensor([2]),requires_grad=True)
y = x+2
z = y**2+3
z.backward()
print(x.grad)

tensor([8.])


##### Matrix Gradient 

In [19]:
X = Variable(torch.randn(10,20),requires_grad=True)
Y = Variable(torch.randn(10,5),requires_grad=True)
Z = Variable(torch.randn(20,5),requires_grad=True)

In [38]:
W = torch.mean(Y-torch.matmul(X,Z))
W.backward()

In [39]:
print(X.grad)

tensor([[ 0.0288, -0.5435, -0.3920, -0.2973,  0.1810,  0.1454, -0.0022, -0.1901,
         -0.0340, -0.2569, -0.3193,  0.0072, -0.1616, -0.1505,  0.0699, -0.0069,
         -0.2594,  0.3237, -0.2457,  0.0904],
        [ 0.0288, -0.5435, -0.3920, -0.2973,  0.1810,  0.1454, -0.0022, -0.1901,
         -0.0340, -0.2569, -0.3193,  0.0072, -0.1616, -0.1505,  0.0699, -0.0069,
         -0.2594,  0.3237, -0.2457,  0.0904],
        [ 0.0288, -0.5435, -0.3920, -0.2973,  0.1810,  0.1454, -0.0022, -0.1901,
         -0.0340, -0.2569, -0.3193,  0.0072, -0.1616, -0.1505,  0.0699, -0.0069,
         -0.2594,  0.3237, -0.2457,  0.0904],
        [ 0.0288, -0.5435, -0.3920, -0.2973,  0.1810,  0.1454, -0.0022, -0.1901,
         -0.0340, -0.2569, -0.3193,  0.0072, -0.1616, -0.1505,  0.0699, -0.0069,
         -0.2594,  0.3237, -0.2457,  0.0904],
        [ 0.0288, -0.5435, -0.3920, -0.2973,  0.1810,  0.1454, -0.0022, -0.1901,
         -0.0340, -0.2569, -0.3193,  0.0072, -0.1616, -0.1505,  0.0699, -0.0069,
      

In [44]:
print(Y.grad)

tensor([[0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200],
        [0.1200, 0.1200, 0.1200, 0.1200, 0.1200]])


In [42]:
print(Z.grad)

tensor([[-0.5783, -0.5783, -0.5783, -0.5783, -0.5783],
        [-0.3016, -0.3016, -0.3016, -0.3016, -0.3016],
        [-0.6875, -0.6875, -0.6875, -0.6875, -0.6875],
        [-0.8098, -0.8098, -0.8098, -0.8098, -0.8098],
        [ 0.6637,  0.6637,  0.6637,  0.6637,  0.6637],
        [-0.3077, -0.3077, -0.3077, -0.3077, -0.3077],
        [ 0.1771,  0.1771,  0.1771,  0.1771,  0.1771],
        [ 0.3535,  0.3535,  0.3535,  0.3535,  0.3535],
        [ 0.3589,  0.3589,  0.3589,  0.3589,  0.3589],
        [-0.4463, -0.4463, -0.4463, -0.4463, -0.4463],
        [ 0.0749,  0.0749,  0.0749,  0.0749,  0.0749],
        [-0.1118, -0.1118, -0.1118, -0.1118, -0.1118],
        [-0.1906, -0.1906, -0.1906, -0.1906, -0.1906],
        [-0.9002, -0.9002, -0.9002, -0.9002, -0.9002],
        [-0.3898, -0.3898, -0.3898, -0.3898, -0.3898],
        [-0.7185, -0.7185, -0.7185, -0.7185, -0.7185],
        [-0.5733, -0.5733, -0.5733, -0.5733, -0.5733],
        [-0.0898, -0.0898, -0.0898, -0.0898, -0.0898],
        [ 

##### Complex auto gradient

Let $n=(n_0,n_1)=(m_0^2,m_1^3)$, where $m_0=2,m_1=3$

In [88]:
# define m and n
m = Variable(torch.FloatTensor([[2,3]]),requires_grad=True)
n = Variable(torch.zeros(1,2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [89]:
# update the n value based
n[0,0] = m[0,0]**2
n[0,1] = m[0,1]**3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [93]:
n.backward(torch.ones_like(n))

In [95]:
print(m.grad)

tensor([[ 4., 27.]])


##### Multiple auto gradient

$y=x+2x^2+3$

In [108]:
x = Variable(torch.FloatTensor([3]),requires_grad=True)
y = x+2*x**2+3
print(y)

tensor([24.], grad_fn=<AddBackward0>)


In [109]:
y.backward(retain_graph=True) # keep value in graph 

In [110]:
print(x.grad)

tensor([13.])


In [111]:
y.backward(retain_graph=True) # keep again

In [112]:
print(x.grad)

tensor([26.])


In [113]:
y.backward() # this time do not keep

In [114]:
print(x.grad)

tensor([39.])


If $K = (x_0^2+3x_1,2x_0+x_1^2)$, find $\nabla K$ as gradient matrix

In [213]:
x = Variable(torch.FloatTensor([2, 3]), requires_grad=True)
k = Variable(torch.zeros(2))

k[0] = x[0]**2+3*x[1]
k[1] = x[1]**2+2*x[0]

In [214]:
print(k)

tensor([13., 13.], grad_fn=<CopySlices>)


In [215]:
# define 0 matrix 2x2
j = torch.zeros(2, 2)

k.backward(torch.FloatTensor([1, 0]),retain_graph=True)
j[0] = x.grad.data

In [216]:
x.grad.data.zero_() # set x.grad to 0
k.backward(torch.FloatTensor([0, 1]))
j[1] = x.grad.data

In [218]:
print(j)

tensor([[4., 3.],
        [2., 6.]])


##### More complex auto gradient

In [254]:
x = Variable(torch.FloatTensor([[2,1]]), requires_grad=True)
y = Variable(torch.FloatTensor([[1,2],[3,4]]), requires_grad=True)

In [255]:
z = torch.mm(x,y)
print(f"z:{z}")
z.backward(torch.FloatTensor([[1,0]]),retain_graph=True)
print(x.grad)
print(y.grad)

z:tensor([[5., 8.]], grad_fn=<MmBackward>)
tensor([[1., 3.]])
tensor([[2., 0.],
        [1., 0.]])


In [256]:
z.backward(torch.FloatTensor([[0,1]]))
print(x.grad)
print(y.grad)

tensor([[3., 7.]])
tensor([[2., 2.],
        [1., 1.]])
