In [1]:
import torch
import numpy as np

In [2]:
# define a numpy ndarray
numpy_tensor = np.random.randn(10,20)

In [3]:
numpy_tensor.shape

(10, 20)

In [4]:
# transfer numpy to torch
torch_tensor1 = torch.Tensor(numpy_tensor)
torch_tensor2 = torch.from_numpy(numpy_tensor)

In [5]:
# transfer torch to numpy
numpy_array = torch_tensor1.numpy() # if is on cpu
# numpy_array = torch_tensor1.cpu().numpy() # if is on GPU
# tensor cannot transfer to numpy if is on gpu, you must transfer to cpu first

In [6]:
torch_tensor1.dim()

2

In [7]:
torch_tensor1.type()

'torch.FloatTensor'

In [8]:
torch_tensor1.numel()

200

In [9]:
# exericise
x = torch.randn(3,2)
x = x.type(torch.DoubleTensor)
x_array = x.numpy()
print(x_array.dtype)

float64


In [10]:
x = torch.ones(2,2)

In [11]:
x = torch.randn(4,3)

In [12]:
print(x)

tensor([[ 0.7401,  0.1388,  0.2688],
        [-0.7769, -0.6346,  0.3261],
        [-0.9913,  0.3047, -0.7221],
        [-1.5253,  0.3211,  0.5887]])


In [13]:
# get max and min
max_value, max_index = torch.max(x,dim=1)

In [14]:
print(max_value)
print(max_index)

tensor([0.7401, 0.3261, 0.3047, 0.5887])
tensor([0, 2, 1, 2])


In [15]:
# get sum of x
sum_x = torch.sum(x,dim=1)
print(sum_x)

tensor([ 1.1477, -1.0855, -1.4087, -0.6154])


In [16]:
# add dimension
print(x.shape)
x = x.unsqueeze(0)
print(x.shape)

torch.Size([4, 3])
torch.Size([1, 4, 3])


In [17]:
x = x.unsqueeze(1)
print(x.shape)

torch.Size([1, 1, 4, 3])


In [18]:
# reduce dimension
x = x.squeeze(0)
x.shape

torch.Size([1, 4, 3])

In [19]:
x = x.squeeze() # reduce all dim
x.shape

torch.Size([4, 3])

In [20]:
x = torch.randn(3,4,5)
print(x.shape)

torch.Size([3, 4, 5])


In [21]:
x = x.permute(1,0,2) # reorder dim 
print(x.shape)
x = x.transpose(0,2) # switch dim
print(x.shape) 

torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


In [22]:
# view can use to reshape tensor
x = torch.randn(3,4,5)
print(x.shape)

x = x.view(-1,5) # -1 means random dim, 5 means second dim is 5
print(x.shape)

x = x.view(3,20) # re shape to 3x20
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


In [23]:
x = torch.randn(3,3)
y = torch.randn(3,3)
z = x + y
print(x)
print(y)
print(z)

tensor([[-0.1963,  0.0677, -0.3183],
        [-0.4452, -0.4715, -1.6934],
        [-0.7134, -0.3806, -0.2055]])
tensor([[ 0.4666, -0.3352,  0.5884],
        [-0.3566, -0.6051, -0.2945],
        [ 1.8451, -0.8873, -0.4383]])
tensor([[ 0.2703, -0.2675,  0.2701],
        [-0.8018, -1.0766, -1.9879],
        [ 1.1317, -1.2680, -0.6438]])


In [24]:
# inplace can directly work on tensor instead create a new space
x = torch.ones(3,3)
print(x.shape) # 3x3

# unsqueeze, add one dim
x.unsqueeze_(0)
print(x.shape)

# transpose for inplace
x.transpose_(1,0)
print(x.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])
torch.Size([3, 1, 3])


In [25]:
x = torch.ones(3,3)
y = torch.ones(3,3)

# add for inplace
x.add_(y)
print(x)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [26]:
# create a float32, 4x4 with value 1 matrix, make mid part of 2x2 matrix with value 2
x = torch.ones(4,4)
x[1:3,1:3] = 2
print(x)

tensor([[1., 1., 1., 1.],
        [1., 2., 2., 1.],
        [1., 2., 2., 1.],
        [1., 1., 1., 1.]])


In [27]:
# Variable library, variable can be used to gradient and any computing
from torch.autograd import Variable

In [28]:
# define x and y
x_tensor = torch.randn(10,5)
y_tensor = torch.randn(10,5)

# change x and y to Variable
x = Variable(x_tensor,requires_grad = True) # default is False for gradient computing
y = Variable(y_tensor,requires_grad = True)

In [29]:
x_tensor

tensor([[-0.7712, -0.7839,  0.4109, -0.9062, -1.1328],
        [-0.6476, -0.5942, -0.6395, -0.5944, -0.4326],
        [ 2.4189, -1.2772,  0.9217,  1.6366,  0.1529],
        [-0.6225,  0.2183, -1.6846, -0.4087, -0.9298],
        [-1.0261, -0.4803,  1.1796, -0.6097,  1.6232],
        [ 0.4040,  0.0857,  0.5899,  0.3641,  1.6551],
        [ 0.2213,  1.3893,  0.3508,  0.0155, -0.1462],
        [-0.8073, -0.6651,  0.3530, -0.1435,  1.2507],
        [-1.0479,  1.2841,  0.5221,  3.3117,  0.4125],
        [-0.0973,  0.4449,  1.0721, -1.5630,  0.4907]])

In [30]:
x

tensor([[-0.7712, -0.7839,  0.4109, -0.9062, -1.1328],
        [-0.6476, -0.5942, -0.6395, -0.5944, -0.4326],
        [ 2.4189, -1.2772,  0.9217,  1.6366,  0.1529],
        [-0.6225,  0.2183, -1.6846, -0.4087, -0.9298],
        [-1.0261, -0.4803,  1.1796, -0.6097,  1.6232],
        [ 0.4040,  0.0857,  0.5899,  0.3641,  1.6551],
        [ 0.2213,  1.3893,  0.3508,  0.0155, -0.1462],
        [-0.8073, -0.6651,  0.3530, -0.1435,  1.2507],
        [-1.0479,  1.2841,  0.5221,  3.3117,  0.4125],
        [-0.0973,  0.4449,  1.0721, -1.5630,  0.4907]], requires_grad=True)

In [31]:
y

tensor([[ 5.9615e-01, -5.6166e-01, -6.2805e-02, -1.1026e-02,  8.1156e-01],
        [-1.1450e+00, -8.5012e-01, -5.3636e-03,  9.7425e-02,  4.3636e-01],
        [-9.1270e-01, -1.9881e-01,  1.9575e-01, -1.6785e+00,  2.9871e-01],
        [-1.1734e+00,  3.0056e-01,  1.5261e+00,  1.9138e+00,  3.3328e-01],
        [ 1.4146e+00,  1.2869e+00, -3.4578e-01,  1.1452e+00, -1.4659e-01],
        [ 9.2307e-01,  1.3098e+00, -2.1884e+00, -1.0055e-01, -1.0560e-01],
        [ 5.7744e-01, -2.9881e+00,  2.9203e-03,  4.8728e-01, -2.0900e-01],
        [-6.8064e-01, -1.8849e-01, -1.4033e-02,  2.8841e-01,  1.2400e+00],
        [-5.6516e-01, -1.4018e-01,  1.2789e+00,  1.0602e+00,  1.2621e+00],
        [-1.1304e+00, -2.9121e-01,  1.0679e-01, -2.4331e-01, -2.6870e-01]],
       requires_grad=True)

In [32]:
x+y

tensor([[-1.7505e-01, -1.3456e+00,  3.4808e-01, -9.1721e-01, -3.2121e-01],
        [-1.7926e+00, -1.4443e+00, -6.4484e-01, -4.9700e-01,  3.7362e-03],
        [ 1.5062e+00, -1.4760e+00,  1.1174e+00, -4.1923e-02,  4.5157e-01],
        [-1.7959e+00,  5.1890e-01, -1.5844e-01,  1.5051e+00, -5.9652e-01],
        [ 3.8849e-01,  8.0663e-01,  8.3382e-01,  5.3544e-01,  1.4766e+00],
        [ 1.3270e+00,  1.3955e+00, -1.5985e+00,  2.6357e-01,  1.5495e+00],
        [ 7.9878e-01, -1.5988e+00,  3.5376e-01,  5.0275e-01, -3.5518e-01],
        [-1.4879e+00, -8.5362e-01,  3.3898e-01,  1.4489e-01,  2.4906e+00],
        [-1.6130e+00,  1.1439e+00,  1.8010e+00,  4.3719e+00,  1.6746e+00],
        [-1.2277e+00,  1.5364e-01,  1.1789e+00, -1.8063e+00,  2.2198e-01]],
       grad_fn=<AddBackward0>)

In [33]:
z = torch.sum(x+y)

In [34]:
print(z.data)
print(z.grad_fn)

tensor(7.4557)


In [35]:
# find gradient of x and y
z.backward()

In [36]:
print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [37]:
# create a function y = x^2 and find the gradient of y
import matplotlib.pyplot as plt
x = np.arange(-3,3.01,0.1)
y = x**2
plt.plot(x,y)
plt.plot(2,4,'ro')
plt.show()

<Figure size 640x480 with 1 Axes>

In [38]:
x = Variable(torch.FloatTensor([2]), requires_grad = True)
y = x**2
y.backward()
print(x.grad)
print(y.grad_fn)

tensor([4.])
