In [1]:
import torch
from torch.autograd import Variable

$z = (x+2)^2+3$\
$z'=2(x+2)$\
If x = 2, $z'=8$

In [2]:
x = Variable(torch.Tensor([2]),requires_grad=True)
y = x+2
z = y**2+3
z.backward()
print(x.grad)

tensor([8.])


##### Matrix Gradient 

In [3]:
X = Variable(torch.randn(10,20),requires_grad=True)
Y = Variable(torch.randn(10,5),requires_grad=True)
Z = Variable(torch.randn(20,5),requires_grad=True)

In [4]:
W = torch.mean(Y-torch.matmul(X,Z))
W.backward()

In [5]:
print(X.grad)

tensor([[-0.0865,  0.0366, -0.0284,  0.0127, -0.0507,  0.0026, -0.0071, -0.0116,
          0.0735, -0.0040, -0.1033,  0.0684,  0.0208,  0.0048,  0.0525,  0.0427,
         -0.0458, -0.0718,  0.0005,  0.0457],
        [-0.0865,  0.0366, -0.0284,  0.0127, -0.0507,  0.0026, -0.0071, -0.0116,
          0.0735, -0.0040, -0.1033,  0.0684,  0.0208,  0.0048,  0.0525,  0.0427,
         -0.0458, -0.0718,  0.0005,  0.0457],
        [-0.0865,  0.0366, -0.0284,  0.0127, -0.0507,  0.0026, -0.0071, -0.0116,
          0.0735, -0.0040, -0.1033,  0.0684,  0.0208,  0.0048,  0.0525,  0.0427,
         -0.0458, -0.0718,  0.0005,  0.0457],
        [-0.0865,  0.0366, -0.0284,  0.0127, -0.0507,  0.0026, -0.0071, -0.0116,
          0.0735, -0.0040, -0.1033,  0.0684,  0.0208,  0.0048,  0.0525,  0.0427,
         -0.0458, -0.0718,  0.0005,  0.0457],
        [-0.0865,  0.0366, -0.0284,  0.0127, -0.0507,  0.0026, -0.0071, -0.0116,
          0.0735, -0.0040, -0.1033,  0.0684,  0.0208,  0.0048,  0.0525,  0.0427,
      

In [6]:
print(Y.grad)

tensor([[0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200]])


In [7]:
print(Z.grad)

tensor([[-1.2556e-02, -1.2556e-02, -1.2556e-02, -1.2556e-02, -1.2556e-02],
        [-1.5873e-01, -1.5873e-01, -1.5873e-01, -1.5873e-01, -1.5873e-01],
        [-9.3289e-02, -9.3289e-02, -9.3289e-02, -9.3289e-02, -9.3289e-02],
        [ 3.0366e-02,  3.0366e-02,  3.0366e-02,  3.0366e-02,  3.0366e-02],
        [ 1.3616e-02,  1.3616e-02,  1.3616e-02,  1.3616e-02,  1.3616e-02],
        [ 2.9275e-02,  2.9275e-02,  2.9275e-02,  2.9275e-02,  2.9275e-02],
        [-1.1621e-01, -1.1621e-01, -1.1621e-01, -1.1621e-01, -1.1621e-01],
        [-3.9812e-02, -3.9812e-02, -3.9812e-02, -3.9812e-02, -3.9812e-02],
        [-6.2025e-02, -6.2025e-02, -6.2025e-02, -6.2025e-02, -6.2025e-02],
        [ 4.5474e-02,  4.5474e-02,  4.5474e-02,  4.5474e-02,  4.5474e-02],
        [-1.0592e-04, -1.0592e-04, -1.0592e-04, -1.0592e-04, -1.0592e-04],
        [ 2.9024e-02,  2.9024e-02,  2.9024e-02,  2.9024e-02,  2.9024e-02],
        [ 3.2798e-02,  3.2798e-02,  3.2798e-02,  3.2798e-02,  3.2798e-02],
        [-1.1993e-02, -1.

##### Complex auto gradient

Let $n=(n_0,n_1)=(m_0^2,m_1^3)$, where $m_0=2,m_1=3$

In [8]:
# define m and n
m = Variable(torch.FloatTensor([[2,3]]),requires_grad=True)
n = Variable(torch.zeros(1,2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [9]:
# update the n value based
n[0,0] = m[0,0]**2
n[0,1] = m[0,1]**3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [10]:
n.backward(torch.ones_like(n))

In [11]:
print(m.grad)

tensor([[ 4., 27.]])


##### Multiple auto gradient

$y=x+2x^2+3$

In [12]:
x = Variable(torch.FloatTensor([3]),requires_grad=True)
y = x+2*x**2+3
print(y)

tensor([24.], grad_fn=<AddBackward0>)


In [13]:
y.backward(retain_graph=True) # keep value in graph 

In [14]:
print(x.grad)

tensor([13.])


In [15]:
y.backward(retain_graph=True) # keep again

In [16]:
print(x.grad)

tensor([26.])


In [17]:
y.backward() # this time do not keep

In [18]:
print(x.grad)

tensor([39.])


If $K = (x_0^2+3x_1,2x_0+x_1^2)$, find $\nabla K$ as gradient matrix

In [19]:
x = Variable(torch.FloatTensor([2, 3]), requires_grad=True)
k = Variable(torch.zeros(2))

k[0] = x[0]**2+3*x[1]
k[1] = x[1]**2+2*x[0]

In [20]:
print(k)

tensor([13., 13.], grad_fn=<CopySlices>)


In [21]:
# define 0 matrix 2x2
j = torch.zeros(2, 2)

k.backward(torch.FloatTensor([1, 0]),retain_graph=True)
j[0] = x.grad.data

In [22]:
x.grad.data.zero_() # set x.grad to 0
k.backward(torch.FloatTensor([0, 1]))
j[1] = x.grad.data

In [23]:
print(j)

tensor([[4., 3.],
        [2., 6.]])


##### More complex auto gradient

In [24]:
x = Variable(torch.FloatTensor([[2,1]]), requires_grad=True)
y = Variable(torch.FloatTensor([[1,2],[3,4]]), requires_grad=True)

In [25]:
z = torch.mm(x,y)
print(f"z:{z}")
z.backward(torch.FloatTensor([[1,0]]),retain_graph=True)
print(x.grad)
print(y.grad)

z:tensor([[5., 8.]], grad_fn=<MmBackward>)
tensor([[1., 3.]])
tensor([[2., 0.],
        [1., 0.]])


In [26]:
z.backward(torch.FloatTensor([[0,1]]))
print(x.grad)
print(y.grad)

tensor([[3., 7.]])
tensor([[2., 2.],
        [1., 1.]])
